apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
      - name: tasky
        image: 650251718485.dkr.ecr.us-west-2.amazonaws.com/tasky:28
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-uri
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: LoadBalancer
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
